### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by timoerlemans** [burst-digital/headless.ninja#6]
You're SSL certificate is invalid.

**Comment by bartlangelaan** [comment]
The website is currently hosted on GitHub Pages. Github Pages doesn't support https for all custom domains yet (also see isaacs/github#156). 

It looks like GitHub is actively working on this issue (a lot of custom domains already have it) but they didn't announce anything officially.

We could set up Cloudflare to use https in the mean time.

**Comment by bartlangelaan** [comment]
The page is now served with Cloudflare, and http is being redirected to https!
